# Generated by Django 3.1.3 on 2021-08-16 18:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio for a user of the platform to describe their situation.', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=users.models.select_storage, upload_to=users.models.image_filename),
        ),
        migrations.AddField(
            model_name='user',
            name='sublet_status',
            field=models.IntegerField(choices=[(10, 'None'), (20, 'Searching'), (30, 'Offering')], default=10),
        ),
    ]
