# Generated by Django 3.1.3 on 2020-11-27 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accommodation_type', models.IntegerField(choices=[(1, 'Apartment'), (2, 'House'), (3, 'Condominium')], default=1, help_text='The type of building the listing is for.')),
                ('start_date', models.DateField(help_text='The first date that the subletter may move in.')),
                ('end_date', models.DateField(help_text='The date by which the subletter must leave.')),
                ('address', models.CharField(help_text='The string representation of the address of the building the listing is for.', max_length=255)),
                ('additional_info', models.TextField(blank=True, help_text='Optional additional information about the listing that is not covered by the other fields.')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bed_type', models.IntegerField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Queen'), (4, 'King')], default=1, help_text='The type of bed that this room is equipped with.')),
                ('ensuite', models.BooleanField(default=False, help_text='A boolean to indicate whether or not this room has an ensuite bathroom.')),
                ('minifridge', models.BooleanField(default=False, help_text='A boolean to indicate whether or not this room comes with a mini-fridge.')),
                ('listing', models.ForeignKey(help_text='The listing that this room belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='listings.listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
