# Generated by Django 3.1.3 on 2020-12-02 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the institution, i.e. University of Waterloo.', max_length=255, unique=True)),
                ('address', models.CharField(help_text='The street address of the institution.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(help_text="The actual domain of an institution's email address, for example: uwaterloo.ca", max_length=255, unique=True)),
                ('institution', models.ForeignKey(help_text='The institution that this domain is for.', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='institutions.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
